### ISSUE TITLE
Add support for other languages

### ISSUE THREAD

**Issue by RulHolos** [Shezwick/GlamourSpamBeGone#1]
This only works for the english version of the game.

You could consider adding a language check at startup and check the message content this way instead of hardcoding it.

For reference, in french:
"You cast a glamour." -> "Vous projetez un mirage."
"Glamours projected from plate " -> "Vous vous équipez de la tenue "

**Comment by Shezwick** [comment]
omg i completely overlooked the other language options. thanks for bringing it up, i'll have an update ready for testing within a few days!

**Comment by Shezwick** [comment]
Hi, this feature was just added to the testing builds as version 1.1.0.0. Everything should check out. Unless I find anything wrong, I plan to push the plugin to stable later this week
